"use client";

/**
 * ObservationGrid — Excel-like spreadsheet for phenotyping data entry.
 *
 * Rows are pre-generated by the backend from Trial × Environments × Replications.
 * Rows with record_id = null are empty plot slots (never recorded yet).
 * On first cell edit of an empty row, the caller auto-creates an ObservationRecord.
 */

import {
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
  type CSSProperties,
  type KeyboardEvent as ReactKeyboardEvent,
} from "react";
import {
  useReactTable,
  getCoreRowModel,
  getSortedRowModel,
  getFilteredRowModel,
  createColumnHelper,
  flexRender,
  type ColumnDef,
  type Column,
  type SortingState,
  type ColumnFiltersState,
  type ColumnPinningState,
  type VisibilityState,
} from "@tanstack/react-table";
import { useVirtualizer } from "@tanstack/react-virtual";
import {
  ChevronUp,
  ChevronDown,
  ChevronsUpDown,
  Columns3,
  Pin,
  PinOff,
  Eye,
  Trash2,
  Loader2,
  Check,
  AlertCircle,
} from "lucide-react";
import { cn } from "@/lib/utils";
import type { Characteristic, GridRow } from "@/types";

// ── Constants ────────────────────────────────────────────────────────────────

const LS_VISIBILITY_KEY = "obs-grid-col-visibility-v3";
const LS_PINNING_KEY    = "obs-grid-col-pinning-v3";

const DEFAULT_PINNED: string[] = [
  "plot_no",
  "genotype_code",
  "genotype_name",
  "environment_code",
  "replication",
];

const STATIC_META_COLS = [
  "plot_no",
  "genotype_code",
  "genotype_name",
  "environment_code",
  "replication",
];

const COL_LABELS: Record<string, string> = {
  plot_no:          "No Plot",
  genotype_code:    "Kode Gen",
  genotype_name:    "Gen",
  environment_code: "Lokasi",
  replication:      "R",
};

const COL_WIDTHS: Record<string, number> = {
  plot_no:          68,
  genotype_code:    80,
  genotype_name:    90,
  environment_code: 88,
  replication:      40,
};

const ROW_HEIGHT = 34;

// ── Types ────────────────────────────────────────────────────────────────────

interface ObservationGridProps {
  rows:            GridRow[];
  characteristics: Characteristic[];
  isLoading?:      boolean;
  canEdit?:        boolean;
  onCellChange:    (row: GridRow, characteristic: Characteristic, value: number | null) => Promise<void>;
  onViewRow?:      (row: GridRow) => void;
  onDeleteRow?:    (row: GridRow) => void;
}

interface RowData {
  row:              GridRow;
  plot_no:          string;
  genotype_code:    string;
  genotype_name:    string;
  environment_code: string;
  replication:      number;
  [charCode: string]: unknown;
}

type CellSaveStatus = "saving" | "saved" | "error";

interface ActiveCell {
  rowIdx:     number;
  charColIdx: number;
}

// ── Helpers ──────────────────────────────────────────────────────────────────

function cellKey(row: GridRow, charCode: string) {
  return `${row.genotype_id}:${row.environment_id}:${row.replication}:${charCode}`;
}

function getPinningStyles<T>(column: Column<RowData, T>, isHeader = false): CSSProperties {
  const isPinned = column.getIsPinned();
  if (!isPinned) return isHeader ? { zIndex: 1 } : {};
  return {
    position: "sticky",
    left: `${column.getStart("left")}px`,
    width: `${column.getSize()}px`,
    minWidth: `${column.getSize()}px`,
    maxWidth: `${column.getSize()}px`,
    zIndex: isHeader ? 30 : 20,
    backgroundColor: isHeader ? "rgb(249,250,251)" : "rgb(255,255,255)",
    boxShadow: "inset -1px 0 0 rgb(209,213,219), 3px 0 8px -3px rgba(0,0,0,0.10)",
  };
}

function loadFromLS<T>(key: string, fallback: T): T {
  try {
    const raw = localStorage.getItem(key);
    return raw ? (JSON.parse(raw) as T) : fallback;
  } catch { return fallback; }
}

function saveToLS(key: string, value: unknown) {
  try { localStorage.setItem(key, JSON.stringify(value)); } catch {}
}

const columnHelper = createColumnHelper<RowData>();

// ── Component ─────────────────────────────────────────────────────────────────

export function ObservationGrid({
  rows,
  characteristics,
  isLoading,
  canEdit = true,
  onCellChange,
  onViewRow,
  onDeleteRow,
}: ObservationGridProps) {
  // ── Table state ────────────────────────────────────────────────────────────
  const [sorting,          setSorting]          = useState<SortingState>([]);
  const [columnFilters,    setColumnFilters]    = useState<ColumnFiltersState>([]);
  const [columnVisibility, setColumnVisibility] = useState<VisibilityState>(
    () => loadFromLS<VisibilityState>(LS_VISIBILITY_KEY, {})
  );
  const [columnPinning, setColumnPinning] = useState<ColumnPinningState>(
    () => loadFromLS<ColumnPinningState>(LS_PINNING_KEY, { left: DEFAULT_PINNED })
  );
  const [showColumnMenu, setShowColumnMenu] = useState(false);

  useEffect(() => saveToLS(LS_VISIBILITY_KEY, columnVisibility), [columnVisibility]);
  useEffect(() => saveToLS(LS_PINNING_KEY, columnPinning), [columnPinning]);

  // ── Spreadsheet state ──────────────────────────────────────────────────────
  const [activeCell,  setActiveCell]  = useState<ActiveCell | null>(null);
  const [editingCell, setEditingCell] = useState<ActiveCell | null>(null);
  const [editValue,   setEditValue]   = useState<string>("");
  const [cellStatus,  setCellStatus]  = useState<Record<string, CellSaveStatus>>({});

  const containerRef = useRef<HTMLDivElement>(null);
  const inputRef     = useRef<HTMLInputElement>(null);

  // ── Data ──────────────────────────────────────────────────────────────────
  const data = useMemo<RowData[]>(
    () =>
      rows.map((r) => ({
        row:              r,
        plot_no:          r.plot_no,
        genotype_code:    r.genotype.genotype_code,
        genotype_name:    r.genotype.genotype_name,
        environment_code: r.environment.name ?? r.environment.environment_code,
        replication:      r.replication,
        ...Object.fromEntries(characteristics.map((c) => [c.code, r.values?.[c.code] ?? null])),
      })),
    [rows, characteristics]
  );

  const charLabelMap = useMemo(
    () => Object.fromEntries(characteristics.map((c) => [c.code, c.name])),
    [characteristics]
  );

  // ── Columns ────────────────────────────────────────────────────────────────
  const columns = useMemo<ColumnDef<RowData, unknown>[]>(() => {
    const staticCols = STATIC_META_COLS.map((id) =>
      columnHelper.accessor((row) => row[id as keyof RowData] as string | number, {
        id,
        size: COL_WIDTHS[id] ?? 80,
        header: COL_LABELS[id] ?? id,
        cell: (info) => (
          <span className={cn(
            "text-xs select-none",
            id === "environment_code"
              ? "block whitespace-normal break-words max-w-[88px]"
              : "whitespace-nowrap"
          )}>
            {info.getValue() as string | number}
          </span>
        ),
      })
    );

    const charCols = characteristics.map((c) =>
      columnHelper.accessor((row) => row[c.code] as number | null, {
        id:                 c.code,
        size:               72,
        enableColumnFilter: false,
        header: () => (
          <div className="text-center leading-tight" title={`${c.name}${c.unit ? ` (${c.unit})` : ""}`}>
            <div>{c.code}</div>
            {c.unit && <div className="text-[10px] text-gray-400 normal-case font-normal">({c.unit})</div>}
          </div>
        ),
        cell: () => null,
      })
    );

    const aksiCol: ColumnDef<RowData, unknown>[] =
      onViewRow || onDeleteRow
        ? [{
            id:                  "__aksi__",
            size:                72,
            header:              "Aksi",
            enableSorting:       false,
            enableColumnFilter:  false,
            cell: ({ row }) => {
              const gridRow = row.original.row;
              const hasRecord = gridRow.record_id !== null;
              return (
                <div className="flex items-center gap-1">
                  {onViewRow && hasRecord && (
                    <button
                      onClick={() => onViewRow(gridRow)}
                      className="p-1.5 rounded hover:bg-blue-50 text-blue-400 transition"
                      title="Detail"
                    >
                      <Eye className="w-3.5 h-3.5" />
                    </button>
                  )}
                  {canEdit && onDeleteRow && hasRecord && (
                    <button
                      onClick={() => onDeleteRow(gridRow)}
                      className="p-1.5 rounded hover:bg-red-50 text-red-400 transition"
                      title="Hapus"
                    >
                      <Trash2 className="w-3.5 h-3.5" />
                    </button>
                  )}
                </div>
              );
            },
          }]
        : [];

    return [...staticCols, ...charCols, ...aksiCol] as ColumnDef<RowData, unknown>[];
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [characteristics, canEdit, onViewRow, onDeleteRow]);

  // ── Table ─────────────────────────────────────────────────────────────────
  const table = useReactTable({
    data,
    columns,
    state:                    { sorting, columnFilters, columnVisibility, columnPinning },
    onSortingChange:          setSorting,
    onColumnFiltersChange:    setColumnFilters,
    onColumnVisibilityChange: setColumnVisibility,
    onColumnPinningChange:    setColumnPinning,
    getCoreRowModel:     getCoreRowModel(),
    getSortedRowModel:   getSortedRowModel(),
    getFilteredRowModel: getFilteredRowModel(),
  });

  const tableRows = table.getRowModel().rows;

  // ── Virtualisation ─────────────────────────────────────────────────────────
  const rowVirtualizer = useVirtualizer({
    count:            tableRows.length,
    getScrollElement: () => containerRef.current,
    estimateSize:     () => ROW_HEIGHT,
    overscan:         12,
  });

  const virtualItems   = rowVirtualizer.getVirtualItems();
  const totalVirtHeight = rowVirtualizer.getTotalSize();
  const paddingTop     = virtualItems[0]?.start ?? 0;
  const paddingBottom  = totalVirtHeight - (virtualItems[virtualItems.length - 1]?.end ?? 0);

  // ── Visible characteristic columns ─────────────────────────────────────────
  const visibleCharCols = useMemo(
    () =>
      table
        .getVisibleLeafColumns()
        .filter((col) => !STATIC_META_COLS.includes(col.id) && col.id !== "__aksi__"),
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [columnVisibility, characteristics, table]
  );

  // ── Save ───────────────────────────────────────────────────────────────────
  const commitSave = useCallback(
    async (gridRow: GridRow, char: Characteristic, value: number | null) => {
      const key = cellKey(gridRow, char.code);
      setCellStatus((s) => ({ ...s, [key]: "saving" }));
      try {
        await onCellChange(gridRow, char, value);
        setCellStatus((s) => ({ ...s, [key]: "saved" }));
        setTimeout(
          () => setCellStatus((s) => { const n = { ...s }; delete n[key]; return n; }),
          1800
        );
      } catch {
        setCellStatus((s) => ({ ...s, [key]: "error" }));
      }
    },
    [onCellChange]
  );

  // ── Edit mode ──────────────────────────────────────────────────────────────
  const startEdit = useCallback(
    (cell: ActiveCell, initialChar?: string) => {
      if (!canEdit) return;
      const row = tableRows[cell.rowIdx];
      if (!row) return;
      const col = visibleCharCols[cell.charColIdx];
      if (!col) return;
      const current = row.original.row.values?.[col.id] ?? null;
      setEditValue(initialChar ?? (current !== null ? String(current) : ""));
      setEditingCell(cell);
    },
    [canEdit, tableRows, visibleCharCols]
  );

  const commitEdit = useCallback(() => {
    if (!editingCell) return;
    const row = tableRows[editingCell.rowIdx];
    const col = visibleCharCols[editingCell.charColIdx];
    if (!row || !col) { setEditingCell(null); return; }
    const char = characteristics.find((c) => c.code === col.id);
    if (!char) { setEditingCell(null); return; }
    const trimmed = editValue.trim();
    const num = trimmed === "" ? null : Number(trimmed.replace(",", "."));
    const rounded = num !== null && !isNaN(num) ? Number(num.toFixed(char.decimal_places)) : null;
    setEditingCell(null);
    setEditValue("");
    void commitSave(row.original.row, char, rounded);
  }, [editingCell, tableRows, visibleCharCols, characteristics, editValue, commitSave]);

  // ── Navigation ─────────────────────────────────────────────────────────────
  const navigate = useCallback(
    (dRow: number, dCol: number) => {
      setActiveCell((prev) => {
        const cur = prev ?? { rowIdx: 0, charColIdx: 0 };
        const totalRows = tableRows.length;
        const totalCols = visibleCharCols.length;
        if (totalRows === 0 || totalCols === 0) return prev;
        let r = cur.rowIdx    + dRow;
        let c = cur.charColIdx + dCol;
        if (c < 0)         { r -= 1; c = totalCols - 1; }
        if (c >= totalCols) { r += 1; c = 0; }
        r = Math.max(0, Math.min(totalRows - 1, r));
        c = Math.max(0, Math.min(totalCols - 1, c));
        rowVirtualizer.scrollToIndex(r, { align: "auto" });
        return { rowIdx: r, charColIdx: c };
      });
    },
    [tableRows.length, visibleCharCols.length, rowVirtualizer]
  );

  // ── Keyboard ───────────────────────────────────────────────────────────────
  const handleKeyDown = useCallback(
    (e: ReactKeyboardEvent<HTMLDivElement>) => {
      if (editingCell) {
        if (e.key === "Escape") { e.preventDefault(); setEditingCell(null); setEditValue(""); return; }
        if (e.key === "Enter")  { e.preventDefault(); commitEdit(); navigate(1, 0); return; }
        if (e.key === "Tab")    { e.preventDefault(); commitEdit(); navigate(0, e.shiftKey ? -1 : 1); return; }
        return;
      }
      if (!activeCell) return;
      if (e.key === "ArrowUp")    { e.preventDefault(); navigate(-1, 0); }
      if (e.key === "ArrowDown")  { e.preventDefault(); navigate(1, 0); }
      if (e.key === "ArrowLeft")  { e.preventDefault(); navigate(0, -1); }
      if (e.key === "ArrowRight") { e.preventDefault(); navigate(0, 1); }
      if (e.key === "Tab")        { e.preventDefault(); navigate(0, e.shiftKey ? -1 : 1); return; }
      if (e.key === "Enter")      { e.preventDefault(); startEdit(activeCell); return; }
      if (e.key === "PageUp")     { e.preventDefault(); navigate(-10, 0); }
      if (e.key === "PageDown")   { e.preventDefault(); navigate(10, 0); }
      if (e.key === "Home")       { e.preventDefault(); setActiveCell((p) => p ? { ...p, charColIdx: 0 } : p); }
      if (e.key === "End")        { e.preventDefault(); setActiveCell((p) => p ? { ...p, charColIdx: visibleCharCols.length - 1 } : p); }
      if (e.key === "Delete" || e.key === "Backspace") {
        e.preventDefault();
        if (!canEdit) return;
        const row = tableRows[activeCell.rowIdx];
        const col = visibleCharCols[activeCell.charColIdx];
        if (!row || !col) return;
        const char = characteristics.find((c) => c.code === col.id);
        if (char) void commitSave(row.original.row, char, null);
        return;
      }
      if (canEdit && /^[\d.\-]$/.test(e.key)) { e.preventDefault(); startEdit(activeCell, e.key); }
    },
    [activeCell, editingCell, navigate, commitEdit, startEdit, tableRows, visibleCharCols, characteristics, commitSave, canEdit]
  );

  // ── Paste ──────────────────────────────────────────────────────────────────
  const handlePaste = useCallback(
    (e: React.ClipboardEvent<HTMLDivElement>) => {
      if (!activeCell || !canEdit) return;
      const text = e.clipboardData.getData("text/plain");
      if (!text) return;
      e.preventDefault();
      const pastedRows = text
        .replace(/\r\n/g, "\n").replace(/\r/g, "\n")
        .trim().split("\n").map((r) => r.split("\t"));
      pastedRows.forEach((pastedRow, rOffset) => {
        const rowIdx = activeCell.rowIdx + rOffset;
        if (rowIdx >= tableRows.length) return;
        const gridRow = tableRows[rowIdx].original.row;
        pastedRow.forEach((rawVal, cOffset) => {
          const charIdx = activeCell.charColIdx + cOffset;
          if (charIdx >= visibleCharCols.length) return;
          const col  = visibleCharCols[charIdx];
          const char = characteristics.find((c) => c.code === col.id);
          if (!char) return;
          const cleaned = rawVal.trim().replace(",", ".");
          const num = cleaned === "" ? null : Number(cleaned);
          if (num !== null && isNaN(num)) return;
          const rounded = num !== null ? Number(num.toFixed(char.decimal_places)) : null;
          void commitSave(gridRow, char, rounded);
        });
      });
    },
    [activeCell, canEdit, tableRows, visibleCharCols, characteristics, commitSave]
  );

  useEffect(() => {
    if (editingCell) requestAnimationFrame(() => inputRef.current?.focus());
  }, [editingCell]);

  // Close column menu on outside click
  useEffect(() => {
    if (!showColumnMenu) return;
    const handler = (e: MouseEvent) => {
      const menu = document.getElementById("obs-col-menu");
      if (menu && !menu.contains(e.target as Node)) setShowColumnMenu(false);
    };
    document.addEventListener("mousedown", handler);
    return () => document.removeEventListener("mousedown", handler);
  }, [showColumnMenu]);

  const allLeafCols = table.getAllLeafColumns();

  // ── Render ─────────────────────────────────────────────────────────────────
  return (
    <div className="space-y-2 outline-none" tabIndex={0} onKeyDown={handleKeyDown} onPaste={handlePaste}>
      {/* Toolbar */}
      <div className="flex items-center justify-between gap-2 flex-wrap">
        {canEdit ? (
          <p className="hidden md:block text-[11px] text-gray-400">
            Klik sel → pilih · Klik 2× / Enter → edit · Tab / ↑↓←→ → navigasi · Ctrl+V → tempel dari Excel
          </p>
        ) : (
          <p className="text-[11px] text-gray-400">Mode baca saja</p>
        )}

        <div className="relative ml-auto">
          <button
            onClick={() => setShowColumnMenu((v) => !v)}
            className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium border border-gray-200 rounded-lg hover:bg-gray-50 transition"
          >
            <Columns3 className="w-3.5 h-3.5" /> Kolom
          </button>

          {showColumnMenu && (
            <div
              id="obs-col-menu"
              className="absolute right-0 top-9 z-50 w-64 max-w-[82vw] max-h-80 overflow-y-auto bg-white border border-gray-200 rounded-lg shadow-xl p-2"
            >
              <div className="flex gap-1.5 mb-2 pb-2 border-b border-gray-100">
                <button
                  onClick={() => allLeafCols.forEach((c) => c.toggleVisibility(true))}
                  className="flex-1 text-xs py-1 px-2 rounded bg-green-50 text-green-700 hover:bg-green-100 transition"
                >
                  Pilih Semua
                </button>
                <button
                  onClick={() =>
                    allLeafCols
                      .filter((c) => !DEFAULT_PINNED.includes(c.id) && c.id !== "__aksi__")
                      .forEach((c) => c.toggleVisibility(false))
                  }
                  className="flex-1 text-xs py-1 px-2 rounded bg-gray-50 text-gray-600 hover:bg-gray-100 transition"
                >
                  Batal Semua
                </button>
              </div>
              {allLeafCols.map((col) => {
                const isPinned = col.getIsPinned();
                const label = COL_LABELS[col.id] ?? charLabelMap[col.id] ?? col.id;
                return (
                  <div key={col.id} className="flex items-center justify-between gap-2 px-2 py-1.5 rounded hover:bg-gray-50">
                    <label className="flex items-center gap-2 flex-1 min-w-0 cursor-pointer text-sm">
                      <input
                        type="checkbox"
                        checked={col.getIsVisible()}
                        onChange={col.getToggleVisibilityHandler()}
                        className="accent-green-600"
                      />
                      <span className="truncate">{label}</span>
                    </label>
                    <button
                      onClick={() => col.pin(isPinned ? false : "left")}
                      title={isPinned ? "Lepas pin" : "Pin kolom"}
                      className="flex-shrink-0 text-gray-400 hover:text-green-600 transition"
                    >
                      {isPinned ? <Pin className="w-3.5 h-3.5 fill-current" /> : <PinOff className="w-3.5 h-3.5" />}
                    </button>
                  </div>
                );
              })}
            </div>
          )}
        </div>
      </div>

      {/* Table */}
      <div
        ref={containerRef}
        className="overflow-auto rounded-lg border border-gray-200"
        style={{ maxHeight: "72vh", isolation: "isolate" }}
      >
        <table
          className="min-w-full border-separate border-spacing-0 text-sm"
          style={{ height: `${totalVirtHeight + 48}px`, position: "relative" }}
        >
          <thead className="bg-gray-50" style={{ position: "sticky", top: 0, zIndex: 40 }}>
            {table.getHeaderGroups().map((hg) => (
              <tr key={hg.id}>
                {hg.headers.map((header) => (
                  <th
                    key={header.id}
                    style={getPinningStyles(header.column, true)}
                    className="px-2 py-2 text-left text-xs font-semibold text-gray-500 uppercase tracking-wide border-b border-gray-200 bg-gray-50"
                  >
                    {header.isPlaceholder ? null : (
                      <div className="space-y-1">
                        <button
                          onClick={header.column.getToggleSortingHandler()}
                          className={cn(
                            "flex items-center gap-1 w-full",
                            header.column.getCanSort() && "cursor-pointer select-none"
                          )}
                        >
                          {flexRender(header.column.columnDef.header, header.getContext())}
                          {header.column.getCanSort() &&
                            ({
                              asc:  <ChevronUp   className="w-3 h-3 text-green-600" />,
                              desc: <ChevronDown className="w-3 h-3 text-green-600" />,
                            }[header.column.getIsSorted() as string] ??
                              <ChevronsUpDown className="w-3 h-3 text-gray-300" />)}
                        </button>
                        {header.column.getCanFilter() && (
                          <input
                            value={(header.column.getFilterValue() as string) ?? ""}
                            onChange={(e) => header.column.setFilterValue(e.target.value)}
                            placeholder="Filter…"
                            className="w-full px-1 py-0.5 text-[11px] font-normal normal-case border border-gray-200 rounded focus:outline-none focus:ring-1 focus:ring-green-400"
                            onClick={(e) => e.stopPropagation()}
                          />
                        )}
                      </div>
                    )}
                  </th>
                ))}
              </tr>
            ))}
          </thead>

          <tbody className="bg-white">
            {isLoading ? (
              [...Array(8)].map((_, i) => (
                <tr key={i} style={{ height: ROW_HEIGHT }}>
                  {table.getAllLeafColumns().map((col) => (
                    <td key={col.id} className="px-2 py-1">
                      <div className="h-4 bg-gray-100 rounded animate-pulse" />
                    </td>
                  ))}
                </tr>
              ))
            ) : tableRows.length === 0 ? (
              <tr>
                <td
                  colSpan={table.getAllLeafColumns().length}
                  className="px-4 py-10 text-center text-gray-400 text-sm"
                >
                  Tidak ada data. Pastikan Research Plan sudah memiliki genotipe dan lokasi.
                </td>
              </tr>
            ) : (
              <>
                {paddingTop > 0 && (
                  <tr><td colSpan={table.getAllLeafColumns().length} style={{ height: paddingTop }} /></tr>
                )}

                {virtualItems.map((vItem) => {
                  const row      = tableRows[vItem.index];
                  const rowIdx   = vItem.index;
                  const gridRow  = row.original.row;
                  const isEmpty  = gridRow.record_id === null;

                  return (
                    <tr
                      key={row.id}
                      style={{ height: ROW_HEIGHT }}
                      className={cn("group", isEmpty && "bg-amber-50/40")}
                    >
                      {row.getVisibleCells().map((cell) => {
                        const isPinned   = cell.column.getIsPinned();
                        const isCharCol  = !STATIC_META_COLS.includes(cell.column.id) && cell.column.id !== "__aksi__";
                        const charColIdx = isCharCol
                          ? visibleCharCols.findIndex((c) => c.id === cell.column.id)
                          : -1;

                        const isSelected = isCharCol && activeCell?.rowIdx === rowIdx && activeCell?.charColIdx === charColIdx;
                        const isEditing  = isCharCol && editingCell?.rowIdx === rowIdx && editingCell?.charColIdx === charColIdx;

                        const statusKey = isCharCol ? cellKey(gridRow, cell.column.id) : "";
                        const status    = isCharCol ? cellStatus[statusKey] : undefined;

                        // ── Characteristic cell ──────────────────────────────
                        if (isCharCol && charColIdx >= 0) {
                          const char  = characteristics.find((c) => c.code === cell.column.id);
                          const value = gridRow.values?.[cell.column.id] ?? null;

                          return (
                            <td
                              key={cell.id}
                              style={getPinningStyles(cell.column)}
                              className={cn(
                                "px-0 py-0 relative border-b border-gray-50",
                                !isPinned && !isSelected && !isEditing && "group-hover:bg-gray-50/60",
                              )}
                            >
                              {isEditing ? (
                                <input
                                  ref={inputRef}
                                  type="number"
                                  step="any"
                                  value={editValue}
                                  autoFocus
                                  onChange={(e) => setEditValue(e.target.value)}
                                  onBlur={commitEdit}
                                  onKeyDown={(e) => {
                                    if (e.key === "Escape") { e.preventDefault(); e.stopPropagation(); setEditingCell(null); setEditValue(""); }
                                    if (e.key === "Enter")  { e.preventDefault(); e.stopPropagation(); commitEdit(); navigate(1, 0); }
                                    if (e.key === "Tab")    { e.preventDefault(); e.stopPropagation(); commitEdit(); navigate(0, e.shiftKey ? -1 : 1); }
                                  }}
                                  className="w-full h-full px-1.5 text-right text-sm font-mono bg-blue-50 border-2 border-blue-400 rounded focus:outline-none"
                                  style={{ minWidth: 64 }}
                                />
                              ) : (
                                <div
                                  className={cn(
                                    "w-full h-full flex items-center justify-end px-1.5 cursor-default select-none text-sm font-mono",
                                    isSelected
                                      ? "ring-2 ring-inset ring-blue-400 bg-blue-50/80"
                                      : canEdit && "hover:bg-blue-50/30",
                                    status === "error" && "bg-red-50",
                                  )}
                                  style={{ minHeight: ROW_HEIGHT }}
                                  onClick={() => {
                                    if (isSelected) startEdit({ rowIdx, charColIdx });
                                    else setActiveCell({ rowIdx, charColIdx });
                                  }}
                                  onDoubleClick={() => { setActiveCell({ rowIdx, charColIdx }); startEdit({ rowIdx, charColIdx }); }}
                                >
                                  <span className={value === null ? "text-gray-300" : "text-gray-800"}>
                                    {value !== null
                                      ? (char ? value.toFixed(char.decimal_places) : String(value))
                                      : "—"}
                                  </span>
                                  {status === "saving" && <Loader2 className="ml-1 w-3 h-3 text-blue-400 animate-spin flex-shrink-0" />}
                                  {status === "saved"  && <Check       className="ml-1 w-3 h-3 text-green-500 flex-shrink-0" />}
                                  {status === "error"  && <AlertCircle className="ml-1 w-3 h-3 text-red-500 flex-shrink-0" />}
                                </div>
                              )}
                            </td>
                          );
                        }

                        // ── Static / Aksi cells ──────────────────────────────
                        return (
                          <td
                            key={cell.id}
                            style={{
                              ...getPinningStyles(cell.column),
                              ...(isPinned ? {} : { backgroundColor: isEmpty ? "rgb(255,251,235,0.4)" : "rgb(255,255,255)" }),
                            }}
                            className={cn(
                              "px-2 py-1 whitespace-nowrap border-b border-gray-50",
                              isPinned ? "text-gray-600" : "text-gray-600 group-hover:bg-gray-50/60",
                            )}
                          >
                            {flexRender(cell.column.columnDef.cell, cell.getContext())}
                          </td>
                        );
                      })}
                    </tr>
                  );
                })}

                {paddingBottom > 0 && (
                  <tr><td colSpan={table.getAllLeafColumns().length} style={{ height: paddingBottom }} /></tr>
                )}
              </>
            )}
          </tbody>
        </table>
      </div>

      {/* Footer */}
      <div className="flex items-center justify-between text-xs text-gray-400">
        <span>
          {tableRows.filter((r) => r.original.row.record_id !== null).length} diisi
          {" / "}
          {tableRows.length} baris
        </span>
        {activeCell && (
          <span className="text-blue-500">
            Plot {tableRows[activeCell.rowIdx]?.original.plot_no ?? "?"} ·{" "}
            {visibleCharCols[activeCell.charColIdx]?.id ?? ""}
          </span>
        )}
      </div>
    </div>
  );
}
